### ISSUE TITLE
game crashed bc of xaeros map and xaero plus

### ISSUE THREAD

**Issue by JamingDE** [rfresh2/XaeroPlus#108]
i dont know why this happened, but i does. i send the crash file and the log, if that helps. this happened about 4 times.
[latest.log](https://github.com/rfresh2/XaeroPlus/files/14070393/latest.log)
[crash-2024-01-27_01.35.06-client.txt](https://github.com/rfresh2/XaeroPlus/files/14070395/crash-2024-01-27_01.35.06-client.txt)
i play with a lot of mods, and i dont know if any of the mods caused the issue...

**Comment by rfresh2** [comment]
```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
	at java.base/java.io.DataOutputStream.writeLong(DataOutputStream.java:230)
	at xaero.map.region.texture.RegionTexture.writeCacheMapData(RegionTexture.java:288)
	at xaero.map.region.texture.BranchRegionTexture.writeCacheMapData(BranchRegionTexture.java:306)
	at xaero.map.region.LeveledRegion.saveCacheTextures(LeveledRegion.java:330)
	at xaero.map.file.MapSaveLoad.run(MapSaveLoad.java:1200)
	at xaero.map.MapProcessor.run(MapProcessor.java:349)
	at xaero.map.MapRunner.run(MapRunner.java:18)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

You need to allocate more ram to your mc instance

If you use the vanilla MC launcher you can do this through the JVM arguments like this 

![MinecraftLauncher_qb4IUvSf4F](https://github.com/rfresh2/XaeroPlus/assets/89827146/79aab402-0d69-43f7-a3d4-5e1d8457f323)

**Comment by JamingDE** [comment]
Thank you

rfresh2 ***@***.***> schrieb am Sa., 27. Jan. 2024, 01:46:

**Comment by rfresh2** [comment]
I've reduced some of the memory usage in https://github.com/rfresh2/XaeroPlus/releases/tag/Fabric-1.20.1-80 (you will also need to update xaero worldmap and minimap)

**Comment by JamingDE** [comment]
Awesome, thanks!

rfresh2 ***@***.***> schrieb am Sa., 27. Jan. 2024, 05:15:
