### ISSUE TITLE
1.12.2 crash

### ISSUE THREAD

**Issue by allforone33** [rfresh2/XaeroPlus#145]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from XaeroPlus (xaeroplus)
Caused by: java.lang.VerifyError: Operand stack underflow
Exception Details:
  Location:
    com/github/benmanes/caffeine/cache/BoundedLocalCache.values()Ljava/util/Collection; @0: areturn
  Reason:
    Attempt to pop empty stack.
  Current Frame:
    bci: @0
    flags: { }
    locals: { 'com/github/benmanes/caffeine/cache/BoundedLocalCache' }
    stack: { }
  Bytecode:
    0x0000000: b0                                     

    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)
    at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:87)
    at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalAsyncLoadingCache.<init>(BoundedLocalCache.java:3876)
    at com.github.benmanes.caffeine.cache.Caffeine.buildAsync(Caffeine.java:1203)
    at com.github.benmanes.caffeine.cache.Caffeine.buildAsync(Caffeine.java:1167)
    at xaeroplus.util.highlights.ChunkHighlightBaseCacheHandler.<init>(ChunkHighlightBaseCacheHandler.java:27)
    at xaeroplus.util.highlights.ChunkHighlightLocalCache.<init>(ChunkHighlightLocalCache.java:10)
    at xaeroplus.util.newchunks.NewChunksLocalCache.<init>(NewChunksLocalCache.java:13)
    at xaeroplus.module.impl.NewChunks.<init>(NewChunks.java:25)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at java.lang.Class.newInstance(Class.java:442)
    at xaeroplus.module.ModuleManager.init(ModuleManager.java:19)
    at xaeroplus.XaeroPlus.preInit(XaeroPlus.java:35)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:7101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

No Mixin Metadata is found in the Stacktrace.

**Comment by rfresh2** [comment]
seems like an error in the java version you're using.

try updating the java you have installed here: https://adoptium.net/temurin/releases/?version=8

**Comment by allforone33** [comment]
I actually think it might be an error with the mod fluidlogged API but I will certainly check.

**Comment by allforone33** [comment]
I think redirectioner may be the culprit as to why the mod wasn't working.

https://legacy.curseforge.com/minecraft/mc-mods/redirectionor-retro

**Comment by rfresh2** [comment]
> Oh and one more thing I am pretty sure this mod doesn't work with openj9 and this is a shame since openj9 reduces memory use by quite a lot.

should work with any distribution of java 8

for example i just downloaded openj9 for jdk8 here: https://developer.ibm.com/languages/java/semeru-runtimes/downloads/ and it works fine

**Comment by allforone33** [comment]
yeah I checked it out, it works. It was the redirectioner mod.
